version: '3.8'

services:
  binan-trading:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: binan-trading-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8088:80"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data

networks:
  default:
    driver: bridge
